### ISSUE TITLE
YouTube Filtering Via Auto-Generated Captions Improvement Suggestion

### ISSUE THREAD

**Issue by notanewbie** [richardfrost/AdvancedProfanityFilter#140] opened 2019-05-10 03:17 UTC
Issues are used primarily to track bugs in the project. Feature requests can be submitted either as an issue or [here](https://goo.gl/forms/LTqFpJ0mCTsrgGgf2).

## Description

I noticed that this extension seems to mute videos until the captions no longer have curse words. When the captions are Auto-Generated from YouTube, can you guys change it so that it mutes and stays muted until the next word shows up, since each word appears in the captions as it is spoken?

### Details (Bugs Only)

Browser Name:
Browser Version:
Extension Version:
Operating System:
Site(s) Affected:

### Steps to reproduce (Bugs only)

1.
2.
3.
4.

## Other details

Keep up the good work.

**Comment by richardfrost** [comment] 2019-05-10 04:27
I'm not sure I'm understanding this completely, so if I'm off please let me know where. You like the way that the other videos work, but not the auto-generated subtitles from YouTube? In the videos I've been testing with it seems to work as desired, but if you have some that aren't working I'd be glad to take a look.

Do you think it would work better if the audio stayed muted until the next work shows up?

One thing you can try adjusting right now is set a minimum muting time in the options.

**Comment by richardfrost** [comment] 2019-05-11 02:08
I really like several of your suggestions and am ready to set them to be the defaults:

```
c---sucker --> suckup (was "idiot")
f-- --> gay (was "slur")
f---ot --> gay (was "slur")
f--s --> gays (was "slur")
jack--- --> jerk (was "idiot")
n---a --> bruh (was "ethnic slur")
n---er --> man (was "ethnic slur")
n---ers --> people (was "ethnic slur")
t--s --> chest (was "explative")
tw-- --> dumbo (was "explative")
```

I think I like simplifying this one:
```
g--d--nit --> ah dangit (was goshdangit) = dangit
```

The rest of the suggestions I'm not ready to adjust yet. It is much harder for words that have multiple meanings and no clear substitution. I have a set of sentences/phrases from the web I run the filter through to see if substitutions make sense, and unfortunately these ones fail about the same, or more than the current ones. I did add a couple notes surrounded by square brackets below. I'm open to more suggestions.

Notes: I don't like the current substitutions, but I feel like these new ones don't really make them better.
```
b---h --> whiner (was "jerk") [Doesn't fit all uses.]
bad--- --> bad boy (was "cool") [Gender can make this confusing: "she's a bad boy."]
bast--d --> guy (was "jerk") [Gender can make this confusing: "She's a guy child."]
c--t --> idiot, hard, or politician (was "explative") (hard because of the various contexts) [Maybe leave this one as "expletive"? That would be the only one.]
f--k --> dang, screw, or forget (was "fudge") [Doesn't fit all uses. What about "F"? Or maybe "F---", "freak", "flip", "frick" are some of the others I've heard]
```

I have a "The Good Place" word list that I use sometimes, and I wish it was that simple on some of these, like bench and fork. Maybe I should just use those?

<details>
  <summary>The Good Place Words (Warning: Profanity)</summary>

```json
{
  "words": {
    "ass": { "matchMethod": 0, "repeat": true, "sub": "ash" },
    "asses": { "matchMethod": 0, "repeat": false, "sub": "ashes" },
    "asshole": { "matchMethod": 1, "repeat": true, "sub": "ashhole" },
    "bastard": { "matchMethod": 1, "repeat": true, "sub": "badword" },
    "bitch": { "matchMethod": 1, "repeat": true, "sub": "bench" },
    "cunt": { "matchMethod": 1, "repeat": true, "sub": "expletive" },
    "dammit": { "matchMethod": 1, "repeat": true, "sub": "dangit" },
    "damn": { "matchMethod": 1, "repeat": true, "sub": "dang" },
    "dick": { "matchMethod": 0, "repeat": true, "sub": "dink" },
    "dumbass": { "matchMethod": 0, "repeat": true, "sub": "dumbash" },
    "fuck": { "matchMethod": 1, "repeat": true, "sub": "fork" },
    "god": { "matchMethod": 0, "repeat": false, "sub": "gosh" },
    "hell": { "matchMethod": 0, "repeat": true, "sub": "heck" },
    "piss": { "matchMethod": 1, "repeat": true, "sub": "pee" },
    "pissed": { "matchMethod": 0, "repeat": true, "sub": "ticked" },
    "shit": { "matchMethod": 1, "repeat": true, "sub": "shirt" },
    "slut": { "matchMethod": 1, "repeat": true, "sub": "tramp" },
    "tits": { "matchMethod": 1, "repeat": true, "sub": "chest" },
    "whore": { "matchMethod": 1, "repeat": true, "sub": "tramp" }
  }
}

```
</details>

One thought I'm having right now is changing the default filter mode from substitute back to censor (what it was orginally). It is easier to make a good replacement with it. I did have a few people request to make substitute the default, but maybe that was a hasty decision.

**Comment by notanewbie** [comment] 2019-05-13 01:45
Yes, I think that would be nice! Being able to adjust the time is handy but some people talk faster than others so it's not perfect.

**Comment by richardfrost** [comment] 2019-05-13 23:32
You are definitely right, not everyone talks at the same speed, so this method has issues. Based on your feedback, what if replaced the option for the minimum mute time with number of additional words to mute? That way, you could leave it off (`0`) to match the current default functionality, or set it to `1` or `2` and have it stay muted for that many words after muting.

Example (Filtering `fox`):
```
0: "The quick brown <fox> jumps over the lazy dog"
1: "The quick brown <fox jumps> over the lazy dog"
2: "The quick brown <fox jumps over> the lazy dog"
```

Do you think that system would work better? I personally don't really see a downside to it, and it seems more predictable and practical than setting the minimum mute time when considering different word length, speaking patterns, etc.

@qwertychouskie, do you have any thoughts on this in relation to #121?

**Comment by qwertychouskie** [comment] 2019-05-16 19:05
The problem is that the timing of the auto-captions is very unreliable, e.g. the captions will pause for a second or two then spit multiple words out at once, which is why a minimum time was needed in the first place.

**Comment by richardfrost** [comment] 2019-05-16 21:55
Agreed - it is a tough issue due to inconsistencies. I see 3 different ways to approach this, and I'd love to get a feel for what people think would be the most effective. If you have an opinion or a new idea I might not have thought of, feel free to respond in a comment. If you just want to vote - leave a matching reaction.

### Minimum time from start of filtered word [Current Method] (Voting Reaction: 😕)
- **Pro:** Already implemented
- **Con:** Words have different lengths (ex, if you have a word that takes 1 second, a minimum of 1 second will do nothing), but may be too long for a short word.
- **Con:** Unreliable with different talking speeds.

### Minimum time from start of next word  (Voting Reaction: 🚀)
- **Pro:** Possibly more accurate than the above (current) method because it would set a minimum based on when the next word comes. This removes the unknown for how long the current filtered word is. (Ex: If you have a word that takes 1 second, and you have a minimum of 1 second, it would not start counting until the next word came up, and would then mute for at least a second.)
- **Pro**: Should be more effective at making sure we don't unmute too early.
- **Con:** Partial words can be pretty jarring
- **Con:** Suffers from same issue as other time-related method: We don't know how long it takes for a word, so it may mute half a word, or 3 words.

### Number of words after (Voting Reaction: 👀)
- **Pro:** Accurate to words (at least subtitles). This could lead to a less jarring experience, and a more predictable outcome.
- **Pro:** More consistent, because if you want it to block 2 words after filtering, it would do that regardless of how much of a pause there is between them, or how long they are.
- **Con:** As pointed out, this still isn't perfect because words don't always match up to the audio.

I think it only makes sense to implement one of these methods. I think I'll wait for some feedback before I decide which direction to take this, so don't be shy, voice your opinion!

RFC: @qwertychouskie @notanewbie @duckbrain @ElectricDrake @JJRicks

**Comment by richardfrost** [comment] 2019-06-09 04:56
Thanks for taking the time to vote! I've implemented the second method: **Minimum time from start of next word (Voting Reaction: 🚀)** in version [2.1.5](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.1.5).

Thanks to all those who voted and provided input. I'm going to go ahead and close this, but feel free to provide feedback in this issue.

**Closed by richardfrost** 2019-06-09 04:56 UTC
Labels: Help Wanted, Question
