### ISSUE TITLE
Script 

### ISSUE THREAD

**Issue by Alex-Mirov** [richardfrost/AdvancedProfanityFilter#267] opened 2020-12-15 18:54 UTC
Hello

With firefox 68 on android im getting warning: Unresponsive script prompt when browsing on sites with a lot of images.

Example: 
"www.modelsport.co.uk"
and "google images"

P.S: this warring also happens on stock settings!

**Comment by richardfrost** [comment] 2020-12-20 19:37
Thanks for reporting the issue. I know I've seen this message in the past, but I haven't noticed it for a while. I'll take a look and see if I can reproduce it. If possible, could you share the type of computer you're using, and any relevant specs?

**Comment by Alex-Mirov** [comment] 2020-12-20 20:04
Hello

On the computer it doesn't happens to me, but it only occurs on phones and tablets running on different android versions with firefox 68.

Thanks

**Comment by Alex-Mirov** [comment] 2021-02-10 15:43
Hello

The slowdown bug appears to get worsen and causes temporary hang on google images.

Is there any solution in the future?

Thanks

**Comment by richardfrost** [comment] 2021-02-10 18:48
If its only happening on the android devices, I think its likely due to them having less powerful processors. I tried looking into it about a month ago and wasn't able to replicate getting that warning message, but I'll give it another try.

Unfortunately at this time I can't think of many optimizations to make that wouldn't effect the filter's effectiveness. I'll take another pass though and see if anything pops up. If its happening mostly on image-heavy pages, there is one additional check that is happening that could potentially be causing the slowdown. I'll do a bit of testing with it and see if its worth adding an option to disable filtering image `alt` text.

If there are specific sites where the filter doesn't perform well, you could also disable the filter on that page. I know that isn't a solution, but it might be a good option in some cases.

**Comment by richardfrost** [comment] 2021-05-26 23:03
Closing for now, but as always, if you have any more related questions feel free to reply here or create a new issue.

**Closed by richardfrost** 2021-05-26 23:03 UTC
Labels: Bug
