### ISSUE TITLE
Whole Match and Per-Word matching methods are not working for Cyrillic words.

### ISSUE THREAD

**Issue by angelvardin** [richardfrost/AdvancedProfanityFilter#91] opened 2018-08-04 12:56 UTC
## Description
Whole Match and Per-Word matching methods are not censoring Cyrillic words and they remain the same. Exact Match and Partial Match are working correctly. 

### Details (Bugs Only)
Chrome Version: 68.0.3440.84
Firefox Version: 61.0.1 
Extension Version: 1.0.15
Operating System: Win 10

### Steps to reproduce (Bugs only) 
1. Add new Cyrillic word in the profanity list of the extension.
example words: котка (cat in English), куче (dog in English), врата (door in English),  
прозорец (window in English), маса (table in English)
2. Set matching method of this word to Whole Match.
2. Type censored word in Google or other popular search engine.

**Comment by richardfrost** [comment] 2018-08-27 05:59
I just pushed an update (1.1.0) that should hopefully address this issue. Please let me know once you get the update if the problem is fixed or not.

It turns out the issue is that JavaScript doesn't handle UTF-8 characters inside RegExp (the mechanism the filter uses to identify which words to target) very well. I have introduced a workaround and in my testing have had success. Thanks for pointing out this issue, and hopefully it shouldn't be a problem anymore.

**Comment by richardfrost** [comment] 2018-10-12 05:48
I'm going to go ahead and close this, because I think it was resolved. If not, feel free to re-open the issue.

**Closed by richardfrost** 2018-10-12 05:48 UTC
Labels: Feedback
