### ISSUE TITLE
Feature Request: Option to disable "main" functionality

### ISSUE THREAD

**Issue by DavidSpivey** [richardfrost/AdvancedProfanityFilter#152] opened 2019-07-14 07:59 UTC
I know you said you would probably not break out the video portion of the profanity filter to its own extension, which I respect.

I am experiencing speed issues loading pages such as YouTube, probably due to the nature of the progressively loading comments section. I need the video mute functionality, but can sacrifice the in-page filtering, since I rarely read comments.

I would like to disable the "main" functionality (filtering profanity in-page) but keep the video mute option.

Can this be added, or alternatively, can I unpack the xpi, change a few lines here and there, and repack locally?

**Comment by richardfrost** [comment] 2019-07-17 17:51
Hello @DavidSpivey, Thanks for reaching out! I am happy to look into this for you! 

So, are you looking to only mute audio on supported pages (YouTube, Netflix, etc.), and leave text (aside from subtitles)? Would you like the extension to work on pages without audio support? Just want to make sure I understand what you are looking for.

**Comment by DavidSpivey** [comment] 2019-07-17 19:05
The only reason I am aware that I have an issue is the speed of loading YouTube, and the fact that Firefox is notifying me that your extension is slowing down the page. (This is the only site where it is obvious to me that the extension is causing a problem, though it may be doing so elsewhere as well)

I downloaded the extension for the express purpose of muting videos, so the other functionality is not of value to me at this time. Should it become of value, I would like to enable and disable it whenever, without enabling and disabling the entire extension.

**Comment by DarthFlappy** [comment] 2019-07-18 20:35
I think that you can turn off YouTube comments if you turn on "Restricted Mode".

**Comment by richardfrost** [comment] 2019-07-18 22:15
Thanks @DarthFlappy for the suggestion. I'd be interested in hearing if that helps with the slowdown you are seeing @DavidSpivey. I've put in some time working on adding a mode that only does audio muting instead of text, and it seems to work everywhere except YouTube 🤦‍♂. YouTube is composed of several IFRAMEs, which all run their own context of the filter. I imagine that has something to do with the slowdowns you are seeing. I am expecting the issue isn't related specifically to the comments, but I'd love to hear if the restricted mode helps in your situation at all.

If that doesn't solve the issue, could you share basics of the computer you are seeing this problem on (CPU, RAM, etc)? I haven't been able to get Firefox to tell me that the extension is causing slowdowns, so I'm just guessing where slowdowns might be happening so I know where to focus.

**Comment by DavidSpivey** [comment] 2019-07-19 06:14
Actually, disabling comments using restricted mode does, indeed, prevent the speed problem. Completely.

**Comment by richardfrost** [comment] 2019-07-19 16:49
Well that's good news! I'll see if I can tinker some more this weekend and get something working so you don't have to run in restricted mode.

**Comment by richardfrost** [comment] 2019-07-20 02:53
@DavidSpive: I have an [experimental build](https://github.com/richardfrost/AdvancedProfanityFilter/files/3413186/extension-firefox.zip) that I'd like you to test if you have some time. It adds a new mode in the Audio tab to only mute audio (and disable text-filtering everywhere else). To use it, you'll need to [load a temporary add-on](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox). I'd recommend [backing up your config](https://github.com/richardfrost/AdvancedProfanityFilter/wiki#config) if you've done any customization, and then disable the official extension before testing it.

To enable the new mode, just head to the Audio tab in the options page and select `Only Mute Audio`. Let me know if it helps at all, or any other things you notice with it.

**Comment by DavidSpivey** [comment] 2019-07-22 19:39
Yes, that absolutely solved the problem! Muchos Gracias!

**Comment by richardfrost** [comment] 2019-07-22 19:55
@DavidSpivey Just to clarify, does that change work even when YouTube is not in "restricted mode"? If so I'll get an official build and get it released.

**Comment by DavidSpivey** [comment] 2019-07-22 21:11
I had already turned off restricted mode before installing, so yes.

**Comment by richardfrost** [comment] 2019-07-22 21:17
Perfect, thanks for the response! I'll reply here when the new update is released.

**Comment by DarthFlappy** [comment] 2019-07-22 21:37
Hmm, stuff like http://www.worldslongestwebsite.com/ and
https://en.wikipedia.org/wiki/Special:LongPages
doesn't seem to have any problems with lag.

Your experiential build seem to work for me, but you have to turn on "Advanced Mode"

**Comment by richardfrost** [comment] 2019-07-22 22:38
Just to clarify @DarthFlappy, is the behavior different with the experimental vs the official release? Is that with the audio only mode on, or off?

I'm glad that you usually don't have problems with lag (I don't either). But having an audio only mode could be beneficial for people who might be interested in just having the audio muting feature, so I think its probably worthwhile to pursue.

**Comment by DarthFlappy** [comment] 2019-07-24 14:04
I tested it again on Netflix and YouTube, and now it all works as expected. I was on Mac OS with Firefox 67.0.2 I have no idea why.

But yes, it did get laggy with "a" being a filtered word.
![Untitled](https://user-images.githubusercontent.com/51761369/61800003-34c0f180-adfa-11e9-88f6-1f044395a689.png)

**Comment by richardfrost** [comment] 2019-07-24 15:15
I believe it slowed down a bit with filtering "a", especially if you did a partial match on it (not sure if you did).

I want to be careful not to degrade performance on the main app, so was that with this build with the audio only mode, or the released version? If you could let me know which ones you have tested and the results you saw, that would be helpful.

- Officially Released
- Experimental with Audio Only mode disabled
- Experimental with Audio Only mode enabled

**Comment by richardfrost** [comment] 2019-07-30 04:52
#155 Adds the code for the Audio Only mode. I'm going to leave the pull request up for a bit to see if anyone has more feedback, but I plan to get it merged soon, with a release following shortly after that.

**Comment by richardfrost** [comment] 2019-08-06 04:58
This feature has been added to [2.1.7](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.1.7).

**Closed by richardfrost** 2019-08-06 04:58 UTC
