### ISSUE TITLE
Audio Muting for bbc.co.uk (BBC Iplayer) and uktvplay.uktv.co.uk

### ISSUE THREAD

**Issue by s-hickman** [richardfrost/AdvancedProfanityFilter#336] opened 2021-09-07 22:48 UTC
Hello,
I have been trying to get the extension to work with these sites. I have been able to follow the instructions up to the point of copying the element, but I'm unsure what to do after this. I've been looking at the examples and doing some trial and error but nothing has worked so far. I would appreciate any help.

[bbc.co.uk](https://bbc.co.uk:):
```html
<div id="subtitle_C981_1" class="" style="position: absolute; margin: 0px; box-sizing: border-box; pointer-events: none; width: 76%; height: 15.652%; left: 12%; top: 79.348%; overflow: visible; -webkit-writing-mode: horizontal-tb; writing-mode: horizontal-tb;">
  <div class="p_paragraph" style="font-size: 1.07786em; color: rgb(255, 255, 255); font-style: normal; font-weight: normal; text-align: center; justify-content: center; text-decoration: none; white-space: normal; line-height: 120%; padding-left: 8px; padding-right: 8px; width: 238.469px; height: 40px; margin-left: 162.32px; margin-top: 27.1406px; position: relative; top: 0px; left: 0px;">
    <div class="p_cueDirUniWrapper" style="">
      <span class="" style="background-color: rgb(0, 0, 0); color: rgb(0, 255, 0); display: inline-block; padding-left: 6.38175px; padding-right: 0.25em;">
        No.
      </span>
      <span class="" style="background-color: rgb(0, 0, 0); color: rgb(0, 255, 0); display: inline-block; padding-left: 0.25em; padding-right: 0.25em;">
        Simon's
      </span>
      <span class="" style="background-color: rgb(0, 0, 0); color: rgb(0, 255, 0); display: inline-block; padding-left: 0.25em; padding-right: 6.38175px;">
        hell bent on nailing
      </span>
      <br class="p_lineBreak" style="background-color: black;">
      <span class="" style="background-color: rgb(0, 0, 0); color: rgb(0, 255, 0); display: inline-block; padding-left: 6.38175px; padding-right: 6.38175px;">
        that headship first.
      </span>
    </div>
  </div>
</div>
```

I tried the following but it only hid the subtitles throughout the video and didn't mute them:
```
{
  "www.bbc.co.uk": [
    {
      "mode": "element",
      "tagName": "div",
      "subtitleSelector": "div.p_cueDirUniWrapper"
    }
  ]
}
```

[uktvplay.uktv.co.uk](https://uktvplay.uktv.co.uk):
```html
<div style="position: absolute; inset: 0px; margin: 1.5%;">
  <div class="vjs-text-track-cue vjs-text-track-cue-en"style="text-align: center; font: 16.6px sans-serif; white-space: pre-line; position: absolute; direction: ltr; writing-mode:horizontal-tb; inset: 275.594px 0px 26.4531px; width: 604.312px; height: 30px; background-color: rgba(0, 0, 0, 0);">
    <div style="color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); position: relative; inset: 0px; display: inline; writing-mode: horizontal-tb; unicode-bidi: plaintext; font-family: sans-serif;">
      <span class="white">Last clinic, last patient.</span>
    </div>
  </div>
</div>
```

**Comment by richardfrost** [comment] 2021-09-08 05:11
Welcome @s-hickman! It looks like you've definitely given it a good try. Sorry this part of the extension is quite confusing, and pretty technical.

I'm guessing you've looked at [Custom Audio Muting Site](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Custom-Audio-Muting-Site#custom-audio-site-structure)? Were the above HTML elements found just in the Elements tab of the developer tools, or did you get to them with the breakpoint (2. Element/Text Mode > Bullet-point 4)?

For the BBC one I'll try hopping on a VPN tomorrow and see if I can take a look at it.

I'm not sure I'll be able to do much with the second site as I don't have an account there, but I'll see if what I can do.

**Comment by s-hickman** [comment] 2021-09-08 16:03
Yes, I added the breakpoint as explained in Element/Texo Mode point 4 to get the HTML elements.

**Comment by richardfrost** [comment] 2021-09-08 23:01
Awesome! Could you give this a try:

```json
{
  "www.bbc.co.uk": [
    {
      "mode": "element",
      "tagName": "div",
      "subtitleSelector": "div.p_cueDirUniWrapper span"
    }
  ]
}
```

I haven't had a chance to personally check out the site yet, but based on the info you have I feel like that might work.

If not, I do hope to have some time soon to take a look at it.

**Comment by s-hickman** [comment] 2021-09-08 23:40
That works perfectly. Thank you so much!

**Comment by richardfrost** [comment] 2021-09-17 17:47
@s-hickman You're very welcome!

Since I don't have access to UKTV, here's my guess on a rule that might work (untested):

```json
{
  "uktvplay.uktv.co.uk:": [
    {
      "mode": "element",
      "subtitleSelector": "div.vjs-text-track-cue span",
      "tagName": "div"
    }
  ]
}
```

**Comment by s-hickman** [comment] 2021-09-18 00:44
> @s-hickman You're very welcome!
> 
> Since I don't have access to UKTV, here's my guess on a rule that might work (untested):
> 
> ```json
> {
>   "uktvplay.uktv.co.uk:": [
>     {
>       "mode": "element",
>       "subtitleSelector": "div.vjs-text-track-cue span",
>       "tagName": "div"
>     }
>   ]
> }
> ```

This works on the subtitles (either showing them filtered or unfiltered or hiding them, according to the extension settings) but it doesn't mute the audio.

**Comment by richardfrost** [comment] 2021-09-20 18:15
Interesting... So just to confirm, it isn't muting, and isn't hiding them, right?

Maybe you could do another information gathering mission like you did before, but at a different point in the video? I just tried with a VPN and wasn't able to complete an account for the site, so I probably won't be able to be much help on my end. But if you could copy the `node` again so I can compare and see if there are any differences that would be great.

**Comment by s-hickman** [comment] 2021-09-22 14:29
Ah, actually I think I got confused. I don't think the audio aspect of the extension is having any effect on the subtitles at all on uktvplay. They are filtered but only because of the text filtering side.

I will try to copy the node again when I have some time. Perhaps on a different video in case it makes any difference.

**Comment by s-hickman** [comment] 2021-11-01 23:38
Muting works for me on most sites, such as Amazon, Youtube etc, but not on Netflix at the moment. It hides the subtitles on Netflix but doesn't mute the audio.

Is this the element you mean?
`<div style="color: rgb(255, 255, 255); background-color: rgb(0, 0, 0); position: relative; inset: 0px; display: inline; writing-mode: horizontal-tb; unicode-bidi: plaintext; font-family: sans-serif;"><span class="yellow">a community which had lived for</span>
<span class="yellow">1,000 years was dead.</span></div>`

**Comment by lukefarr** [comment] 2022-01-11 21:34
Hi Richard. I too am trying to do this for BBC Iplayer. I have used the code you pasted here:
{
  "www.bbc.co.uk": [
    {
      "mode": "element",
      "tagName": "div",
      "subtitleSelector": "div.p_cueDirUniWrapper span"
    }
  ]
}

And this works in that it *** the swear words but will not mute the audio. Any other ideas?

**Comment by richardfrost** [comment] 2022-01-11 23:15
@lukefarr Do you think you could send me a screenshot (or copy the HTML) from the page with the captions/subtitles? Right now I can only access bbc.com (I'll probably need a VPN, which I can try to do soon). The rule that you referenced above seems to work fine on bbc.com, but its definitely possible it won't work on the UK variant.

**Comment by lukefarr** [comment] 2022-01-13 18:21
Hi Richard

Hopefully this will work. Here is a screenshot showing the text filter part
is working: Thanks so much
[image: image.png]

**Comment by lukefarr** [comment] 2022-01-13 18:23
[BBC iPlayer - The Tourist - Series 1_ Episode 2.zip](https://github.com/richardfrost/AdvancedProfanityFilter/files/7865106/BBC.iPlayer.-.The.Tourist.-.Series.1_.Episode.2.zip)
![2022-01-13 19_22_19-BBC iPlayer - The Tourist - Series 1_ Episode 2](https://user-images.githubusercontent.com/31075528/149387351-5dc6cb66-ea45-4a04-8d4f-fbb7504e2921.png)

**Comment by richardfrost** [comment] 2022-01-13 23:48
Thanks @lukefarr for sending that over. Unfortunately that doesn't include what I need to troubleshoot it. What would be helpful is if you could get it paused on a screen just like you have in the screenshot, and then open up the Browser's development tools:

- Windows: `Ctrl +Shift +J`
- Mac: `Cmd + Option + J`

Then click on the "Elements" tab, left click on something in the main Elements pane, then begin a search:

- Windows: `Ctrl + F`
- Mac: `Cmd + F`

Then type part of the captions that are being displayed: `like next level` for example. From there, take a screenshot if you can and attach it here. It would also be helpful if you could go up a few levels (meaning those arrows on the left-hand side of the line), right-click on it and choose "Copy > Copy element", and then also add that here.

If you feel like this is too hard/complicated, please reach out to me over email (support @ richardfrost.info - without the spaces) and we can see if there might be a better way to solve this.

I was able to get an account setup, but unfortunately I don't have access to iPlayer because I don't have a TV License, so that isn't very helpful.

**Comment by ahkelly** [comment] 2022-01-21 02:35
<div class="p_paragraph" style="font-size: 0.892461em; color: rgb(255, 255, 255); font-style: normal; font-weight: normal; text-align: center; justify-content: center; text-decoration: none; white-space: normal; line-height: 120%; padding-left: 8px; padding-right: 8px; width: 236.484px; height: 17.125px; margin-left: 104.031px; margin-top: 9.54688px; position: relative; top: 0px; left: 0px;"><div class="p_cueDirUniWrapper" style=""><span class="" style="background-color: rgb(0, 0, 0); color: rgb(255, 255, 0); display: inline-block; padding-left: 5.07525px; padding-right: 5.07525px;">Martin called. I got the promotion.</span></div></div>

**Comment by ahkelly** [comment] 2022-01-21 02:35
`<div class="p_paragraph" style="font-size: 0.892461em; color: rgb(255, 255, 255); font-style: normal; font-weight: normal; text-align: center; justify-content: center; text-decoration: none; white-space: normal; line-height: 120%; padding-left: 8px; padding-right: 8px; width: 236.484px; height: 17.125px; margin-left: 104.031px; margin-top: 9.54688px; position: relative; top: 0px; left: 0px;"><div class="p_cueDirUniWrapper" style=""><span class="" style="background-color: rgb(0, 0, 0); color: rgb(255, 255, 0); display: inline-block; padding-left: 5.07525px; padding-right: 5.07525px;">Martin called. I got the promotion.</span></div></div>`

**Comment by ahkelly** [comment] 2022-01-21 03:10
Another example is below. subtitle editing works perfect, audio does not
`<div class="p_paragraph" style="font-size: 1.1725em; color: rgb(255, 255, 255); font-style: normal; font-weight: normal; text-align: center; justify-content: center; text-decoration: none; white-space: normal; line-height: 120%; padding-left: 8px; padding-right: 8px; width: 252.828px; height: 45px; margin-left: 164.328px; margin-top: 25.1094px; position: relative; top: 0px; left: 0px;">
	<div class="p_cueDirUniWrapper" style="">
		<span class="" style="background-color: rgb(0, 0, 0); color: rgb(255, 255, 255); display: inline-block; padding-left: 6.6665px; padding-right: 6.6665px;">I didn't tell you because</span>
		<br class="p_lineBreak" style="background-color: black;">
		<span class="" style="background-color: rgb(0, 0, 0); color: rgb(255, 255, 255); display: inline-block; padding-left: 6.6665px; padding-right: 6.6665px;">you don't take me seriously.</span>
	</div>
</div>`

**Comment by richardfrost** [comment] 2022-01-25 23:10
@ahkelly 

Thanks for sharing that. It still seems like that config from before should be about right, so there must be something else going on. Do you think you'd be able to follow [these steps](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Custom-Audio-Muting-Site#2-elementtext-mode)? I should just need the `node` values from step 5 (of section 2, which is where that link should take you).

If not, or if you want to try something else, lets try it without modifying the text. If this works, the audio should mute when a filtered word is in the captions/subtitles, but it won't be filtered in the text.

```json
{
  "www.bbc.co.uk": [
    {
      "mode": "element",
      "tagName": "div",
      "subtitleSelector": "div.p_cueDirUniWrapper span",
      "filterSubtitles": false
    }
  ]
}
```

**Comment by ahkelly** [comment] 2022-01-31 18:21
Thank you kindly for the response, oddly enough the above works fine now. I had closed and reopened/refreshed my browser a couple of times to test and can confirm it works for both substituting bad words as well as now audio mute! I actually changed filterSubtitles to true and as I said both work now. Now I am trying to apply same logic to iviewer in Australia (iview.abc.net.au) I'll open another issue for this one.

**Comment by lukefarr** [comment] 2022-02-01 18:39
> @ahkelly
> 
> Thanks for sharing that. It still seems like that config from before should be about right, so there must be something else going on. Do you think you'd be able to follow [these steps](https://github.com/richardfrost/AdvancedProfanityFilter/wiki/Custom-Audio-Muting-Site#2-elementtext-mode)? I should just need the `node` values from step 5 (of section 2, which is where that link should take you).
> 
> If not, or if you want to try something else, lets try it without modifying the text. If this works, the audio should mute when a filtered word is in the captions/subtitles, but it won't be filtered in the text.
> 
> ```json
> {
>   "www.bbc.co.uk": [
>     {
>       "mode": "element",
>       "tagName": "div",
>       "subtitleSelector": "div.p_cueDirUniWrapper span",
>       "filterSubtitles": false
>     }
>   ]
> }
> ```

Hi Richard. So i tried this code in custom sites advanced. The subtitle shows the curse word but does not mute. The extension is doing something as the subtitles are only showing when it detects a curse word, so just muting isnt working for some reason?

**Comment by richardfrost** [comment] 2022-02-01 18:55
@ahkelly Thanks for the feedback! That's awesome that its working for you now. Once you feel it is stable I'll go ahead and add it to the filter (so you won't need the custom config anymore). Also, you can simply remove `"filterSubtitles"` if you want, it defaults to `true`.

@lukefarr What browser are you on? Also, could you share the config you are using? (Options page > Config tab > export button). Feel free to attach it here, or send it in an email to support @ richardfrost.info (remove spaces).

**Comment by lukefarr** [comment] 2022-02-01 19:17
Richard - Genius!

So that works. it mutes and it displays a filtered subtitle! Legendary!

Thanks so so much

**Comment by lukefarr** [comment] 2022-02-01 19:18
PS im probably missing something but I also did a custom site for amazon
prime video in UK. This works fine but just wondering how I include
multiple sites in the custom sites input area?

**Comment by richardfrost** [comment] 2022-02-01 19:31
@lukefarr You're welcome! I'm betting that the issue is the Filter is having a hard time isolating the correct `video` on the page. Without seeing more of the page's HTML I probably won't be able to correct it.

If you or @ahkelly would be willing to send me a screenshot of this output it might help to resolve that so the filler audio can work:

1. With a video playing, right-click on the page and choose "Inspect" from the menu to bring up the developer tools.
2. Search (CTRL+F on Windows) for `<video` (there will likely be more than 1 result)
3. Hover over each `<video` element until you find one that highlights the actual video that is playing.
4. Once you have isolated that one, take a screenshot of the elements page (in the developer tools), with the `<video` section towards the bottom of the page so I can see more of the top, as shown in the example screenshot below

![video-find](https://user-images.githubusercontent.com/1507205/152037811-c87e40f1-afa5-43a6-b0ad-dceabbaf64d4.png)

**Comment by richardfrost** [comment] 2022-02-01 19:35
@lukefarr To have multiple custom config entries you keep one set of the outermost `{` and `}`, and then add a `,` between each entry. So, for example (extra blank lines added for illustrative purposes):

```json
{

  "www.amazon.co.uk": [
    {
      "displayHide": "none",
      "displaySelector": "div.webPlayerContainer div.f35bt6a",
      "displayShow": "",
      "iframe": false,
      "mode": "watcher",
      "parentSelector": "div.webPlayerContainer div span > span",
      "videoSelector": "div.webPlayerElement video[src]"
    }
  ],

  "www.bbc.co.uk": [
    {
      "filterSubtitles": false,
      "mode": "element",
      "subtitleSelector": "div.p_cueDirUniWrapper span",
      "tagName": "div"
    }
  ]

}
```

**Comment by richardfrost** [comment] 2022-02-09 04:17
@s-hickman @lukefarr Does anyone here still care about uktvplay, or is it working for them? If no one cares anymore, I think I'm going to go ahead and close this one.

**Comment by richardfrost** [comment] 2022-02-12 06:34
It looks like another issue got opened for channel4 (#379), so I'm going to go ahead and close this one. Thanks to everyone for the help on this one.

**Closed by richardfrost** 2022-02-12 06:34 UTC
Labels: Enhancement, Audio
